{% set name = "mutmut" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0bb271d60047919db181bebc156b8b4a58013c39518b417cb9739ce693332981

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mutmut = mutmut.__main__:climain

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - glob2
    - parso
    - click
    - pony
    - toml
    - junit-xml ==1.8

test:
  requires:
    - pip
  commands:
    - pip check
    - mutmut --help

about:
  home: https://github.com/boxed/mutmut
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: mutmut - python mutation tester
  description: |
    Mutmut is a mutation testing system for Python,
    with a strong focus on ease of use.
  doc_url: https://mutmut.readthedocs.io/
  dev_url: https://github.com/boxed/mutmut

extra:
  recipe-maintainers:
    - carlodri
