{% set name = "mutmut" %}
{% set version = "3.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d45b3460ce72b4657f7ee11ed4f479deddb7bdb0052863b6feb809f596eb0b5c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mutmut = mutmut.__main__:cli

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - parso
    - click
    - textual
    - setproctitle
    - toml >=0.10.2
    - junit-xml =1.8

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - mutmut --help

about:
  home: https://github.com/boxed/mutmut
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: mutmut - python mutation tester
  description: |
    Mutmut is a mutation testing system for Python,
    with a strong focus on ease of use.
  doc_url: https://mutmut.readthedocs.io/
  dev_url: https://github.com/boxed/mutmut

extra:
  recipe-maintainers:
    - carlodri
