{% set name = "mutmut" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb79411983a55de9f0271c1a3fa31be85ae30f33ade1ab04630f4c7e2dee65a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - mutmut = mutmut.__main__:climain

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - glob2
    - parso
    - click
    - pony
    - toml
    - junit-xml ==1.8

test:
  requires:
    - pip
  commands:
    - pip check
    - mutmut --help

about:
  home: https://github.com/boxed/mutmut
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: mutmut - python mutation tester
  description: |
    Mutmut is a mutation testing system for Python,
    with a strong focus on ease of use.
  doc_url: https://mutmut.readthedocs.io/
  dev_url: https://github.com/boxed/mutmut

extra:
  recipe-maintainers:
    - carlodri
